import { useState, useEffect } from 'react';
import { FileText, Download, Trash2, Calendar, Activity, FileDown } from 'lucide-react';
import { storage } from '../utils/storage';
import { AnalysisResult } from '../types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function Reports() {
  const [history, setHistory] = useState<AnalysisResult[]>([]);

  useEffect(() => {
    loadHistory();
  }, []);

  const loadHistory = () => {
    setHistory(storage.getAnalysisHistory());
  };

  const handleClearHistory = () => {
    if (confirm('Are you sure you want to clear all analysis history?')) {
      storage.clearHistory();
      loadHistory();
    }
  };

  // --- NEW PDF GENERATION FUNCTION ---
  const handleDownloadPDF = (analysis: AnalysisResult) => {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(41, 128, 185);
    doc.text('SHAKTI - Component Report', 20, 20);

    // Component Details
    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text(`Component: ${analysis.componentName}`, 20, 40);
    doc.text(`Analysis Date: ${new Date(analysis.timestamp).toLocaleString()}`, 20, 50);
    doc.text(`Source File: ${analysis.filename}`, 20, 60);

    // Health Summary
    doc.setFillColor(240, 240, 240);
    doc.rect(20, 70, 170, 30, 'F');
    doc.setFontSize(14);
    doc.text(`Health Score: ${analysis.health_score.toFixed(1)}%`, 30, 85);
    doc.text(`Estimated RUL: ${analysis.rul_days.toFixed(0)} Days`, 30, 95);
    
    // Alert Level Badge
    doc.setFontSize(12);
    if(analysis.alert_level === 'OPTIMAL') doc.setTextColor(39, 174, 96);
    else if(analysis.alert_level === 'WARNING') doc.setTextColor(243, 156, 18);
    else doc.setTextColor(192, 57, 43);
    doc.text(`Status: ${analysis.alert_level}`, 120, 85);

    // Top Factors Table
    doc.setTextColor(0, 0, 0);
    doc.text('Critical Risk Factors (Root Cause Analysis):', 20, 120);
    
    const tableData = analysis.top_factors.map(([factor, impact]) => [
      factor.replace(/_/g, ' '),
      `${(impact * 100).toFixed(1)}%`
    ]);

    autoTable(doc, {
      startY: 125,
      head: [['Factor Name', 'Impact Probability']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185] }
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by SubStation AI Predictive Maintenance System', 20, 280);

    doc.save(`Report_${analysis.componentName}_${Date.now()}.pdf`);
  };

  // ... (keep getAlertBadge helper) ...
  const getAlertBadge = (level: string) => {
    const styles = {
      OPTIMAL: 'bg-green-100 text-green-700 border-green-200',
      WARNING: 'bg-yellow-100 text-yellow-700 border-yellow-200',
      CRITICAL: 'bg-red-100 text-red-700 border-red-200',
    };
    return styles[level as keyof typeof styles] || styles.OPTIMAL;
  };

  return (
    // Add a default text color and dark-mode white fallback on the parent
    <div className="space-y-6 text-slate-900 dark:text-white">
      {/* ... (Keep header and stats cards same as before) ... */}
      
      {/* Updated Table Section */}
      {history.length > 0 && (
        <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-slate-50 dark:bg-slate-700 border-b border-slate-200 dark:border-slate-600">
                <tr>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-slate-600 dark:text-slate-300 uppercase tracking-wider">Component</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-slate-600 dark:text-slate-300 uppercase tracking-wider">Date</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-slate-600 dark:text-slate-300 uppercase tracking-wider">Health</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-slate-600 dark:text-slate-300 uppercase tracking-wider">RUL (Days)</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-slate-600 dark:text-slate-300 uppercase tracking-wider">Status</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-slate-600 dark:text-slate-300 uppercase tracking-wider">Report</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
                {history.map((analysis) => (
                  <tr key={analysis.id} className="hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                    <td className="px-6 py-4">
                      <div className="font-medium text-slate-800 dark:text-slate-100">{analysis.componentName}</div>
                      <div className="text-sm text-slate-500 dark:text-slate-400">{analysis.filename}</div>
                    </td>
                    <td className="px-6 py-4 text-sm text-slate-700 dark:text-slate-300">
                      {new Date(analysis.timestamp).toLocaleDateString()}
                    </td>
                    <td className="px-6 py-4">
                      <span className={`font-semibold ${
                        analysis.health_score > 80 ? 'text-green-600 dark:text-green-400' : 
                        analysis.health_score > 50 ? 'text-yellow-600 dark:text-yellow-400' : 'text-red-600 dark:text-red-400'
                      }`}>
                        {analysis.health_score.toFixed(1)}%
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm font-medium text-slate-800 dark:text-slate-100">
                      {analysis.rul_days.toFixed(0)}
                    </td>
                    <td className="px-6 py-4">
                      <span className={`px-3 py-1 rounded-md text-xs font-semibold border ${getAlertBadge(analysis.alert_level)}`}>
                        {analysis.alert_level}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <button
                        onClick={() => handleDownloadPDF(analysis)}
                        className="flex items-center space-x-2 px-3 py-1.5 bg-blue-50 text-blue-600 rounded-md hover:bg-blue-100 transition-colors text-xs font-medium border border-blue-200 dark:bg-slate-700 dark:text-white dark:border-slate-600 dark:hover:bg-slate-600"
                        title="Download PDF Report"
                      >
                        <FileDown className="w-4 h-4" />
                        <span>PDF</span>
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
      
      {/* ... (Keep empty state view same as before) ... */}
    </div>
  );
}